AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AirborneTime
  '

Globals:
  Function:
    Timeout: 900
    MemorySize: 512

Parameters:
  CronExpression:
    Type: String
    Default: cron(0 17 ? * FRI *)
  Password:
    NoEcho: true
    Type: String
    Default: password
  UserName:
    NoEcho: true
    Type: String
    Default: username

Resources:
  AirborneTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: airbornesecrets
      CodeUri: airborne-time
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule:
              Ref: CronExpression
    
  CustomProvision:
    Type: Custom::CustomProvision
    Properties:
      ServiceToken: !GetAtt ProvisionParameterFunction.Arn
      ParameterName: airbornesecrets
      UserName: !Ref UserName
      Password: !Ref Password
  
  ProvisionParameterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: provision
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Role: !GetAtt LambdaExecutionRole.Arn
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
              - ssm:GetParameterHistory
              - ssm:GetParametersByPath
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:DeleteParameter
            Resource: "*"

Outputs:
  AirborneTimeFunction:
    Description: "Airborne Time Lambda Function ARN"
    Value: !GetAtt AirborneTimeFunction.Arn
  AirborneTimeFunctionIamRole:
    Description: "Implicit IAM Role created for Airborne Time function"
    Value: !GetAtt AirborneTimeFunctionRole.Arn
  CustomProvisionArn:
    Description: "The arn for the custom resource"
    Value: !GetAtt CustomProvision.Arn
