AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoWeb

Parameters:
  CronSchedule:
    Type: String
    Default: cron(0 0 17 ? * FRI *)
  UserName:
    Type: String
    NoEcho: true
  Password:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 30

Resources:
  AutoWebFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: auto-web/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      #Environment:
      #  Variables:
      #    DEBUG: "*"
      #    NODE_ENV: dev
      Events:
        EveryFri:
          Type: Schedule
          Properties:
            Schedule: !Ref CronSchedule
  AutoWebSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: fieldglass
      SecretString: !Join [ '', [ '{\"username\":\"', !Ref UserName, '\",\"password\":\"', !Ref Password, '\"}'] ]