AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'AirborneTime
  '

Globals:
  Function:
    Timeout: 900
    MemorySize: 512

Parameters:
  CronExpression:
    Type: String
    Default: cron(0 17 ? * FRI *)
  Password:
    NoEcho: true
    Type: String
    Default: password
  UserName:
    NoEcho: true
    Type: String
    Default: username

Resources:
  AirborneTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 
              !Ref AirborneTimeSecrets
      CodeUri: airborne-time
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule:
              Ref: CronExpression

  AirborneTimeSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: airbornesecrets
      SecretString:
        Fn::Join:
        - ''
        - - '{"username":"'
          - Ref: UserName
          - '","password":"'
          - Ref: Password
          - '"}'

Outputs:
  AirborneTimeFunction:
    Description: "Airborne Time Lambda Function ARN"
    Value: !GetAtt AirborneTimeFunction.Arn
  AirborneTimeFunctionIamRole:
    Description: "Implicit IAM Role created for Airborne Time function"
    Value: !GetAtt AirborneTimeFunctionRole.Arn
