AWSTemplateFormatVersion: '2010-09-09'
Description: 'AutoWeb

  '
Globals:
  Function:
    Timeout: 30
Parameters:
  CronExpression:
    Type: String
    Default: cron(0 17 ? * FRI *)
  Password:
    NoEcho: true
    Type: String
    Default: password
  UserName:
    NoEcho: true
    Type: String
    Default: username
Resources:
  AutoWebFunction:
    Properties:
      CodeUri: auto-web
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule:
              !Ref CronExpression
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  AutoWebSecrets:
    Properties:
      Name: autowebsecrets
      SecretString:
        Fn::Join:
        - ''
        - - '{"username":"'
          - Ref: UserName
          - '","password":"'
          - Ref: Password
          - '"}'
    Type: AWS::SecretsManager::Secret
Transform: AWS::Serverless-2016-10-31
