AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoWeb

Globals:
  Function:
    Timeout: 30

Resources:
  AutoWebFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: auto-web/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        EveryFri:
          Type: Schedule
          Properties:
            Schedule:  cron(0 0 17 ? * FRI *)
